### ISSUE TITLE
Set featured image fail

### ISSUE THREAD

**Issue by bueltge** [bueltge/multisite-global-media#15]
* I open correctly the "Featured Image" iframe
* I open correctly the "Global Media" tab
* I can select correctly a global picture
**But** when i click the button "Set featured Image" the modal closed and nothing happens (not even some javascript errors from the browser console) 

@magicworks kann you help to get your feature with a solid solution. Thanks a lot!

**Comment by bueltge** [comment]
Hi @magicworks 
I don't use custom code. I tested on a default installation with default theme and no plugins. After select an image, it will not load as image, create the relationship from post to image.

**Comment by bueltge** [comment]
I have also the same problem with the last pull request #19 , it is not possible to create the relationship. Also a small note if it is not on a post side.
A note - Notice: Undefined index: _thumbnail_id in /var/www/wp-plugins/multisite-global-media/multisite-global-media.php on line 247

**Comment by marinamat76** [comment]
Hi,
thanks for the new version of the plugin!

Now the featured image start to function, but there is yet some little problem.

First of all, also for me there's the problem that when editing a post that haven't set a featured image yet, this notice appears:

PHP Notice:  Undefined index: _thumbnail_id in /var/www/wp_test/wp-content/plugins/multisite-global-media/multisite-global-media.php on line 247

Also, the first time you set a featured image from "Global Media" for a post, the preview is not visible, you need to save the post for viewing it.
After you can remove and reset the featured image from "Global Media" (in the same post) how many time you want and all work fine!

But apart from this, there a major problem: what's happen if from the main side are removed an image that was used from other sites?
If that image, was used from other sites in the content of the post, the editor can manage that broken image removing the HTML code from the "text" view mode.
But if the image was used as a featured image, an editor can not do anything, because from the interface there is'nt any possibility to intervene.
The administrator need to remove manually from the DB the post_meta "_thumbnail_id" to unlock the situation for the editor

Maybe a solution could be to show the link "Remove featured image" also in case of the image doesn't exists anymore.

Thank's,
Marina.

**Comment by marinamat76** [comment]
Hi @magicworks !
Any news about the problem of "unmanageable" featured image if removed from master site?

Thank's
Marina.

**Comment by mrbm** [comment]
@marinamat76 if an image gets deleted, can the user simply replace the image with something else, save, and then go back to the post and remove the image? I personally haven't used the plugin, but planning to play around.

**Comment by bueltge** [comment]
Please test the new release https://github.com/bueltge/multisite-global-media/releases/tag/0.0.6 and get feedback. Thx.

**Comment by holzhannes** [comment]
I tested Version 0.0.6. If i try to set a featured image for post/page/cpt i am able to select it in the image browser but after selecting it nothing happens.

**Comment by widoz** [comment]
@holzhannes which version of WordPress are you running and are you using additional plugins that may create conflicts?

I tried now in a fresh new installation without any plugin active and using the default 2017 theme. 
I'm not able to replicate your issue. After I select the image from the media global I see it in the metabox.
![featured_image](https://user-images.githubusercontent.com/1917784/46108056-64ed3300-c1dd-11e8-8bb0-531334c4efe0.gif)

**Comment by holzhannes** [comment]
@widoz I am using the current version 4.9.8. I will double check without no other plugins active and the WP 2017 standard theme to figure out which plugin is may causing the error.

**Comment by bueltge** [comment]
A test with the current development version WordPress 5.0-alpha-43660 works fine. Thanks @widoz for the fix.

**Comment by holzhannes** [comment]
If I have look in the server logs I can see this error at the moment when the featured image is set:

`
AH01071: Got error 'PHP message: PHP Notice: Trying to get property 'post_type' of non-object in /.../wp-admin/includes/post.php on line 1390\nPHP message: PHP Notice: Trying to get property 'ID' of non-object in /.../wp-admin/includes/post.php on line 1392\nPHP message: PHP Notice: Trying to get property 'labels' of non-object in /.../wp-admin/includes/post.php on line 1397\nPHP message: PHP Notice: Trying to get property 'set_featured_image' of non-object in /.../wp-admin/includes/post.php on line 1397\nPHP message: PHP Notice: Trying to get property 'labels' of non-object in /.../wp-admin/includes/post.php on line 1431\nPHP message: PHP Notice: Trying to get property 'remove_featured_image' of non-object in /.../wp-admin/includes/post.php on line 1431\nPHP message: PHP Notice: Trying to get property 'ID' of non-object in /.../wp-admin/includes/post.php on line 1448\nPHP message: PHP Fatal error: Uncaught TypeError: Argument 2 passed to MultisiteGlobalMedia\\adminPostThumbnailHtml() must be of the type integer, null given, called in /.../wp-includes/class-wp-hook.php on line 286 and defined in /.../wp-content/plugins/multisite-global-media/multisite-global-media.php:338\nStack trace:\n#0 /.../wp-includes/class-wp-hook.php(286): MultisiteGlobalMedia\\adminPostThumbnailHtml('<p class="hide-...', NULL, 239)\n#1 /.../wp-includes/plugin.php(203): WP_Hook->apply_filters('<p class="hide-...', Array)\n#2 /.../wp-admin/includes/post.php(1448): apply_filters('admin_post_thum...', '<p class="hide-...', NULL, 239)\n#3 /.../wp-content/plugins/multisite-global-media/multisite-global-media.php(358): _wp_post_thumbnail...\n', referer: https://example.com/wp-admin/post.php?post=1333&action=edit
`

**Comment by widoz** [comment]
@holzhannes I don't see any error or notice by set the post thumbnail. 

Are you using the latest master code?

The error seems to be `Uncaught TypeError: Argument 2 passed to MultisiteGlobalMedia\\adminPostThumbnailHtml() must be of the type integer, null given` similar to the  pull request #43 but I'm not able to replicate the issue in php 7.2 with the latest version of the code.

**Comment by holzhannes** [comment]
I manual applied the patch to line 338 from #43 which is not yet in the master and now setting the featured image is possible.

**Comment by widoz** [comment]
This has a patch in #43 but I'd like also to suggest the solution of pull request #46.

**Comment by bueltge** [comment]
#46 is inside the master and ready for test on all your side. Please feedback from all of you. Thanks.

**Comment by bueltge** [comment]
The new version is [0.0.8](https://github.com/bueltge/multisite-global-media/releases/tag/0.0.8) and this version should fix this problem for the enhancement. Please test it and give your feedback here.

**Comment by adrianosg** [comment]
I am using the 0.0.8 version and it still doesn't work with ACF Pro Imagem Fields and Featured Images. I can select the image but when I try to get the url it just prints url() in the code.

I need to get the URL because I use the image in a background.

**Comment by widoz** [comment]
Is this fixed? I'd like to remember we are talking about featured image nothing else.

**Comment by bueltge** [comment]
We should close, to less feedback and in our tests works really well. Thanks for your effort.

**Comment by holzhannes** [comment]
@widoz @bueltge Thank you! Working with 0.1.0-dev-2 and 0.0.8.

**Comment by kempert** [comment]
Hello, with Wordpress 5.2.1, setting the thubnail is not working, the picture only loading the hole time. I habe tested Version 0.0.8 and 0.1.0-dev-2

**Comment by widoz** [comment]
@kempert I think you want to follow #60
